### ISSUE TITLE
Document forest client data needs for FOM

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr_fsa_fingerprint#12]
The data governance process is here: https://apps.nrs.gov.bc.ca/int/confluence/display/AR/Data+Integration?

First step is :

Has the Team identified the data\information required for the business needs?
Has the Team documented the business needs as related to the data sought. (If so provide source/link/documents)

Documented on GitHub wiki:
https://github.com/bcgov/forest-client-api/wiki/Business-Requirements

**Comment by webgismd** [comment]
reviewed this - https://github.com/bcgov/nr-forest-client-api/wiki  I think this looks good for when we want to revisit it.. @mishraomp -- https://quarkus-orcl-245e18-dev.apps.silver.devops.gov.bc.ca/q/swagger-ui/
