### ISSUE TITLE
Create Data Governance Proposal Document

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr_fsa_fingerprint#20]
In order to gain the trust of DBAs, data stewards, data architects, etc. FSA needs a well thought-out data data governance process that applies to APIs that expose data to systems, authenticated (and authorized) users, and the public.

WIP: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAAR/API+Data+Governance

Acceptance criteria:

- [x] Document the requirements for a governance framework
- [x] Propose a simple, github-enabled process to start out with
- [x] Get feedback from stakeholders

**Comment by webgismd** [comment]
This is a tough one, I don't want to see this fall off our plates, and I am interested as to the role @jeff-card team can play in supporting this process. This is a really good start and something to revisit as we loop back on to the forest client api work.

**Comment by jeff-card** [comment]
I'd like to see us continue to litmus test the guide against emerging API requirements and iterate/update as necessary.. with the view of creating this guidance for all NRM teams.  If the custodian owns the contract we just need to ensure it's editor friendly for them.
