### ISSUE TITLE
Find the official data classification for the forest client data

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr_fsa_fingerprint#23]
See comments on this issue for the full story...

TLDR: Forest client data classification was done in a Jira [ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-2249)

**Comment by rparfig** [comment]
Reached out to DBAs (John and Raj). Raj thinks the last classification for the entire database was done 3 years ago. He is trying to get me any information related to a more recent classification done on forest_client. 
John has pointed me out to Cody and the Security team. Security should have the master list, so I have reached to Eric V and Louis Kraak. Awaiting response.

**Comment by ConradBoydElliottGustafson** [comment]
Richard to ask Michelle for some help getting some answers.

**Comment by webgismd** [comment]
https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-16102 request for data classification by Security Team/DBAs

**Comment by ConradBoydElliottGustafson** [comment]
Chantelle and Michelle met with Al Bennet to get the classification. They will be drafting a formal letter and getting him to approve it. Peter Werrall from that group is trying to find the results of the obfuscation effort which would have that data. 
Assuming that Michelle will put that document somewhere good when it is done!

**Comment by gormless87** [comment]
Cody to search DA locations for artifacts by Bruce Bell

**Comment by gormless87** [comment]
@rpardofigueroa - can you provide a link to the current/working data classification so I can close this old ticket with a pointer to the good stuff?

**Comment by rparfig** [comment]
Pete: There have been lots of conversations about the classification of CLIENT earlier this year, but I have not found anything different than this, that is or has been made **_official_**:
https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-2249 

@webgismd : Do you have a more recent version of CLIENT classification?

**Comment by webgismd** [comment]
I honestly don't think there is anything newer than that.. but I dont think much as changed either there. NOR have we a solution to put this information anywhere other than the Jira attachment matrix

**Comment by rparfig** [comment]
That is what I thought. @gormless87 : Is this something useful to you?
@webgismd : I keep thinking we should load this in ER Studio until we build another, better solution. We will need an API to get it out though (ideal, already proposed and approved) .... or a SQL to the repo for the time being

**Comment by gormless87** [comment]
@rparfig - Yes, that helps.
