### ISSUE TITLE
FOM Spatial Submission modify pop-up location

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr_fsa_fingerprint#38]
Currently when clicking on an object, the pop-up will appear at the geographical centre of the object.  This is an issue if you are zoomed in on the map so you don’t see the whole object; the popup may appear off map.  It would be better to show up in the location the user clicked.  Another example is a really long road, in the image below, the red circle denotes where I clicked on the road, and the popup appears well outside the extent of the blocks themselves.

[https://app.zenhub.com/files/452009299/8b54aa4c-f2ff-4092-86ea-bb49cc613823/download](https://app.zenhub.com/files/452009299/8b54aa4c-f2ff-4092-86ea-bb49cc613823/download)

**This issue transferred from Jira (FOM-114)**

**Comment by basilv** [comment]
In progress.

**Comment by gormless87** [comment]
Issue FOM-114 Resolved in Jira
